# Generated by Django 5.0.6 on 2024-05-21 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('subtitlo', models.CharField(max_length=60)),
                ('review', models.TextField(max_length=250)),
                ('autor', models.CharField(max_length=60)),
                ('imagen', models.ImageField(upload_to='')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1)),
                ('fecha', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
