# Generated by Django 5.0.6 on 2024-05-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameReview', '0002_alter_gamereview_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamereview',
            name='review',
            field=models.TextField(max_length=2000),
        ),
    ]
